DM command
ToogaInc/Jeffrey pull request #18
Opened 2023-09-14 13:10 UTC by sjkd23

/dm Command that allows higher ups to DM multiple users at once the same message, through the bot.

- Command works with and without command options.
        - Up to 15 users allowed with command options/shortcut
- Message limit of 1014 chars (embed field limit).
- If only message or only users were specified through command options, informs user that it does not work like that.
- If no message or users were specified in command options, sends embed with buttons, and will direct user to add a message and set all the members they'd like the bot to dm.

2023-09-14 13:12 UTC, sjkd23 commented
A couple of thoughts:

- Maybe a different command name? (like /dmall, or something)
- I'm not sure how DM rate limiting works for discord bots, so may need to set a message recipient cap.
- Has not been tested to DM more than one person (me).

2023-09-15 05:11 UTC, ewang2002 requested changes

2023-09-15 05:11 UTC, ewang2002 commented on src/commands/dm.ts
> +ChatInputCommandInteraction,
formatting

2023-09-15 05:11 UTC, ewang2002 commented on src/utils.ts
> +export async function tryDelete(m: Message): Promise<boolean> {
docs

2023-09-15 05:11 UTC, ewang2002 commented on src/utils.ts
> +export async function tryToDMEmbed(embed: EmbedBuilder, member: User): Promise<boolean>{
docs

2023-09-15 05:11 UTC, ewang2002 commented on src/commands/dm.ts
> +                        time: 60_000,
put into constant

2023-09-15 05:11 UTC, ewang2002 commented on src/commands/dm.ts
> +                    if (DM.length > 0 && DM !== '**__Message too long! (limit: 4096 characters)__**') {
make this string a constant

2023-09-15 05:11 UTC, ewang2002 commented on src/commands/dm.ts
> +         * @param {User[]}users - Object array of all specified discord users.
```suggestion
         * @param {User[]} users - Object array of all specified discord users. 
```

2023-09-15 05:11 UTC, ewang2002 commented on src/commands/dm.ts
> +
spacing

2023-09-24 22:13 UTC, ewang2002 approved these changes
approval given assuming you fix the things I pointed out

2023-09-24 22:13 UTC, ewang2002 commented on src/commands/dm.ts
> +            const msgTooLong = '**__Message too long! (limit: 1024 characters)__**';
Put this outside of the function (like below the `MAX_USERS` const, with same naming convention, i.e., `MSG_TOO_LONG`)

2023-09-24 22:13 UTC, ewang2002 commented on src/commands/dm.ts
> +            const embedMessage = await interaction.reply({ content: 'Please follow the instructions below!', embeds: [startEmbed], components: [startRow] });
This line is pretty long

2023-09-24 22:13 UTC, ewang2002 commented on src/commands/dm.ts
> +                            addMsgEmbed.setFields({ name: '__Current Message:__ ', value: DM });
`'__Current Message:__ '` should be a constant :)

2023-09-24 22:13 UTC, ewang2002 commented on src/commands/dm.ts
> +                            addUsersEmbed.setFields({ name: '__Message Recipients:__ ', value: memberList.join(', ') });
constant

2023-09-24 22:13 UTC, ewang2002 commented on src/commands/dm.ts
> +                    await i.update({})
`deferUpdate` or `deferReply` (look up which one to use)

2023-10-03 19:49 UTC, merged